### ISSUE TITLE
Rules idea? Alphanum of X chars?

### ISSUE THREAD

**Issue by rterwedo** [nyxgeek/nyxgeek-rules#1]
We have a situation where I am not finding any documentation on it. We are trying to scale across multiple machines/job by breaking up the keyspace by complexity. Its a 7 char completely random alphanum pwd.

We created a "wordlist" of 3844 "words" ie all combos of 2 alphanumeric chars (62 * 62 = 3844)

```
aa
ab
ac
..
08
09
00
```
In CONFIG the plan was to set min/max len = 7

For scaling we were planning on creating 3844 rules, where each rule grabbed one line (Line N) from the wordlist followed by any alphanum for the remaining chars. Something like below.

[Line N word]?x?x?x?x?x = Rule N

We can then at the command line, call each different rule, as a distinct job, with all machines setup as clones of each other.

1) What would a rule like this look like (Rule N), I can only find references to Az or A0 (ie all wordlist items, or prepending in all the documentation and examples around the web)

Thanks!

**Comment by winxp5421** [comment]
Well, 2 things here.

1. maybe I'm not understanding what exactly you are trying to accomplish but, from my understanding, you are trying to attack a 7 char random password and split that job into "chunks" across multiple machines and for some reason, you have decided to take the wordlist+rules approach? If that is indeed what you are trying to do why not just use mask attacks? IE `aa?l?l?l?l?l` would result in `aa` plus 5 random characters. aaaaaaa -> aazzzzz

2. There exist programs that utilize a "cluster" environment and handles jobs across multiple machines including concurrently working on a single attack see > https://github.com/s3inlc/hashtopussy

**Comment by rterwedo** [comment]
Hi - Yes we actually ended up using masks when we stumbled upon that, considerably faster as well.  Thanks!

**Comment by nyxgeek** [comment]
Cleaning up and closing.
